### ISSUE TITLE
Timestamp format is wrong in request string

### ISSUE THREAD

**Issue by devjuice** [leizongmin/huobiapi#1]
https://github.com/leizongmin/huobiapi/blob/6b2a1c46eaeb912b735e9767b87bd108bb51807a/client/request.go#L33

This line is incorrect because "time.Now().Format(""2017-05-11T15:19:30") won't give you what you would expect. (Interestingly it works, so probably any salt string would work as well, for now). 

See https://play.golang.org/p/PAXvwvtERcU for the output, and https://stackoverflow.com/questions/20234104/how-to-format-current-time-using-a-yyyymmddhhmmss-format

**Comment by leizongmin** [comment]
Thanks!

**Comment by devjuice** [comment]
Thank you! 👍
